version: '3'
services:
    python-env:
        build:
            context: .config/docker/python
        container_name: "${CONTAINER_NAME}-python-env"
        depends_on:
            - db
        volumes:
            - .:/app
        working_dir: /app
        networks:
            - default
        tty: true

    db:
        image: postgres:latest
        container_name: "${CONTAINER_NAME}"
        environment:
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB}"
        ports:
            - "${PORT}:5432"
        volumes:
            - .config/temp:/imports
            - ./.config/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - default

networks:
    default:
        ipam:
            config:
                - subnet: "${SUBNET}"