# Use the official Python image
FROM python:3.13

# Set the working directory in the container
WORKDIR /app

# Install the required Python packages
RUN pip install gdown
RUN pip install python-dotenv
RUN pip install psycopg2
